Repository BetaPuddi/Fortuna-1, pull requests merged in 2023-11, with the labels that each got.

#72 Lap Counter + Checkpoint System
  Assets/Art/TRACK.meta
  Assets/Art/TRACK/trackcollision.mtl.meta
  Assets/Art/TRACK/trackcollision.obj.meta
  Assets/Art/TRACK/trackvisual.mtl.meta
  Assets/Art/TRACK/trackvisual.obj.meta
  Assets/Prefabs.meta
  Assets/Prefabs/CP.prefab
  Assets/Prefabs/CP.prefab.meta
  Assets/Scripts/CartLap.cs
  Assets/Scripts/CartLap.cs.meta
  Assets/Scripts/LapCheckpoint.cs
  Assets/Scripts/LapCheckpoint.cs.meta
  Assets/Scripts/LapHandle.cs
  Assets/Scripts/LapHandle.cs.meta
  Assets/TestScenes/Jacob/Assets/Animations.meta
  Assets/TestScenes/Matt/MattScene.unity
Labels: programming

#73 Finished Ball Projectile Powerup
  .idea/.idea.Fortuna-1/.idea/workspace.xml
  Assets/Art/TRACK.meta
  Assets/Art/TRACK/trackcollision.mtl.meta
  Assets/Art/TRACK/trackcollision.obj.meta
  Assets/Art/TRACK/trackvisual.mtl.meta
  Assets/Art/TRACK/trackvisual.obj.meta
  Assets/Scripts/PowerupSystem/BallProjectile.cs
  Assets/Scripts/PowerupSystem/PowerupContainer.cs
  Assets/TestScenes/Reece/ReeceScene.unity
  Assets/TestScenes/Reece/TestMaterials/JustGreen.mat
  Assets/TestScenes/Reece/TestPrefabs/BallProjectile.prefab
Labels: design

#74 Main scene consolidation#1
  .idea/.idea.Fortuna-1/.idea/workspace.xml
  Assets/Art/Project_start_screen.png
  Assets/Art/Project_start_screen.png.meta
  Assets/Scenes/Levels/Level01.unity
  Assets/Scenes/Levels/Level01.unity.meta
  Assets/Scenes/MainMenu.unity
  Assets/Scenes/MainMenu.unity.meta
  Assets/Scenes/SampleScene.unity
  Assets/TestScenes/Reece/TestMaterials/Box.mat
  Assets/TestScenes/Reece/TestMaterials/Box.mat.meta
  Assets/TestScenes/Reece/TestMaterials/JustBlack.mat
  Assets/TestScenes/Reece/TestMaterials/JustBlack.mat.meta
  Assets/TestScenes/Reece/TestPrefabs/PowerupBox.prefab
Labels: design

#77 Placed hazards in main scene
  Assets/Prefabs/Hazards.meta
  Assets/Prefabs/Hazards/Hazard.prefab
  Assets/Prefabs/Hazards/Hazard.prefab.meta
  Assets/Prefabs/Hazards/Swing.prefab
  Assets/Prefabs/Hazards/Swing.prefab.meta
  Assets/Prefabs/Hazards/Thwomp.prefab
  Assets/Prefabs/Hazards/Thwomp.prefab.meta
  Assets/Prefabs/SpeedPad.prefab
  Assets/Prefabs/SpeedPad.prefab.meta
  Assets/Scenes/Levels/Level01.unity
  Assets/TestScenes/Jacob/Assets/Animations/Slamming Object.anim
  Assets/TestScenes/Jacob/Assets/Animations/Swing.controller
  Assets/TestScenes/Jacob/Assets/Animations/Swing.controller.meta
  Assets/TestScenes/Jacob/Assets/Animations/Swinging Object.anim
  Assets/TestScenes/Jacob/Assets/Animations/Swinging Object.anim.meta
  Assets/TestScenes/Jacob/Assets/Animations/Thwomp.controller
  Assets/TestScenes/Jacob/JacobScene.unity
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/ProjectSettings.asset
Labels: design

#79 Add files via upload
  Assets/Art/Cassettes/CassettePile.obj
  Assets/Art/Cassettes/CassetteSolo.obj
Labels: art

#80 Add files via upload
  Assets/Art/Eyeballs/EyeballL.obj
  Assets/Art/Eyeballs/EyeballS.obj
Labels: art

#81 Add files via upload
  Assets/Art/Mushrooms/MushFatBS.obj
  Assets/Art/Mushrooms/MushFatL.obj
  Assets/Art/Mushrooms/MushFatLS.obj
  Assets/Art/Mushrooms/MushFatTS.obj
  Assets/Art/Mushrooms/MushRedL.obj
  Assets/Art/Mushrooms/MushRedM.obj
  Assets/Art/Mushrooms/MushRedS.obj
  Assets/Art/Mushrooms/MushTall1.obj
  Assets/Art/Mushrooms/MushTall2.obj
  Assets/Art/Mushrooms/MushTall3.obj
  Assets/Art/Mushrooms/MushTall4.obj
Labels: art

#82 Add files via upload
  Assets/Art/ChessPieces/Bishop.mtl
  Assets/Art/ChessPieces/Bishop.obj
  Assets/Art/ChessPieces/Pawn.mtl
  Assets/Art/ChessPieces/Pawn.obj
  Assets/Art/ChessPieces/Rook.mtl
  Assets/Art/ChessPieces/Rook.obj
Labels: art

#83 Add files via upload
  Assets/Art/ISLANDtemp.obj
  Assets/Art/MOUNTAIN.obj
Labels: art

#84 Audio implementation
  .idea/.idea.Fortuna-1/.idea/workspace.xml
  Assets/Audio/Car.meta
  Assets/Audio/Car/Brakes001.mp3
  Assets/Audio/Car/Brakes001.mp3.meta
  Assets/Audio/Car/Brakes002.mp3
  Assets/Audio/Car/Brakes002.mp3.meta
  Assets/Audio/Car/Brakes003.mp3
  Assets/Audio/Car/Brakes003.mp3.meta
  Assets/Audio/Car/Brakes004.mp3
  Assets/Audio/Car/Brakes004.mp3.meta
  Assets/Audio/Car/RallyEngineStart_01_Editing.mp3
  Assets/Audio/Car/RallyEngineStart_01_Editing.mp3.meta
  Assets/Audio/Car/Rally_Drifting_01.mp3
  Assets/Audio/Car/Rally_Drifting_01.mp3.meta
  Assets/Audio/Car/Rally_Engine_Stop.mp3
  Assets/Audio/Car/Rally_Engine_Stop.mp3.meta
  Assets/Audio/Car/Rally_Noise.mp3
  Assets/Audio/Car/Rally_Noise.mp3.meta
  Assets/Audio/UI.meta
  Assets/Audio/UI/ClickTone_NoReverb_SFX01.wav
  Assets/Audio/UI/ClickTone_NoReverb_SFX01.wav.meta
  Assets/MainMixer.mixer
  Assets/Scripts/AudioSystem.meta
  Assets/Scripts/AudioSystem/AudioManager.cs
  Assets/Scripts/AudioSystem/AudioManager.cs.meta
  Assets/TestScenes/Reece/ReeceScene.unity
  ProjectSettings/AudioManager.asset
Labels: design

#87 Main scene consolidation#2
  Assets/Scenes/Levels/Level01.unity
  Assets/Scenes/MainMenu.unity
  Assets/Scripts/FinishScreen.cs
  Assets/TestScenes/Jacob/Scripts/FinishedScreen.cs
Labels: design

#96 Added Respawn Coroutine for Powerup Box
  Assets/Scripts/PowerupSystem/PowerupBox.cs
  Assets/Scripts/PowerupSystem/PowerupContainer.cs
  Assets/TestScenes/Reece/ReeceScene.unity
  Assets/TestScenes/Reece/TestPrefabs/PowerupBox.prefab
Labels: design

#99 Reece alpha powerup button and audio fix
  .idea/.idea.Fortuna-1/.idea/workspace.xml
  Assets/Audio/GameplaySFX.meta
  Assets/Audio/GameplaySFX/Collect_Arp_SFX01.wav
  Assets/Audio/GameplaySFX/Collect_Arp_SFX01.wav.meta
  Assets/Audio/GameplaySFX/Collect_PitchUp_SFX01.wav
  Assets/Audio/GameplaySFX/Collect_PitchUp_SFX01.wav.meta
  Assets/Audio/UISFX.meta
  Assets/Audio/UISFX/ClickTone_NoReverb_SFX01.wav
  Assets/Audio/UISFX/ClickTone_NoReverb_SFX01.wav.meta
  Assets/Audio/UISFX/ClickTone_SFX01.wav
  Assets/Audio/UISFX/ClickTone_SFX01.wav.meta
  Assets/Audio/VehicleSFX_Car.meta
  Assets/Audio/VehicleSFX_Car/Brakes001.mp3
  Assets/Audio/VehicleSFX_Car/Brakes001.mp3.meta
  Assets/Audio/VehicleSFX_Car/Brakes002.mp3
  Assets/Audio/VehicleSFX_Car/Brakes002.mp3.meta
  Assets/Audio/VehicleSFX_Car/Brakes003.mp3
  Assets/Audio/VehicleSFX_Car/Brakes003.mp3.meta
  Assets/Audio/VehicleSFX_Car/Brakes004.mp3
  Assets/Audio/VehicleSFX_Car/Brakes004.mp3.meta
  Assets/Audio/VehicleSFX_Car/RallyEngineStart_01_Editing.mp3
  Assets/Audio/VehicleSFX_Car/RallyEngineStart_01_Editing.mp3.meta
  Assets/Audio/VehicleSFX_Car/Rally_Drifting_01.mp3
  Assets/Audio/VehicleSFX_Car/Rally_Drifting_01.mp3.meta
  Assets/Audio/VehicleSFX_Car/Rally_Engine_Stop.mp3
  Assets/Audio/VehicleSFX_Car/Rally_Engine_Stop.mp3.meta
  Assets/Audio/VehicleSFX_Car/Rally_Noise.mp3
  Assets/Audio/VehicleSFX_Car/Rally_Noise.mp3.meta
  Assets/Scripts/AudioSystem.meta
  Assets/Scripts/AudioSystem/AudioManager.cs
  Assets/Scripts/AudioSystem/AudioManager.cs.meta
  Assets/Scripts/InputActions.cs
  Assets/Scripts/InputActions.cs.meta
  Assets/Scripts/InputActions.inputactions
  Assets/Scripts/InputActions.inputactions.meta
  Assets/Scripts/PowerupSystem/PowerupContainer.cs
  Assets/TestScenes/Reece/ReeceScene.unity
Labels: design

#101 Respawn-System
  Assets/Scenes/Levels/Level01.unity
  Assets/Scripts/GameRespawn.cs
  Assets/Scripts/GameRespawn.cs.meta
Labels: programming

#113 Adding URP
  Assets/TestScenes/Jacob/Assets/ToonShader.shadergraph
  Assets/TestScenes/Jacob/Assets/ToonShader.shadergraph.meta
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/ShaderGraphSettings.asset
Labels: design

#119 Track pieces
  Assets/Art/BRIDGE picketfence.mtl
  Assets/Art/BRIDGE picketfence.obj
  Assets/Art/MOUNTAIN tunnelled.mtl
  Assets/Art/MOUNTAIN tunnelled.obj
  Assets/Art/TRACK puzzle.mtl
  Assets/Art/TRACK puzzle.obj
Labels: art

#122 Add Post-Processing Package
  .idea/.idea.Fortuna-1/.idea/workspace.xml
  Assets/Art/BRIDGE picketfence.mtl.meta
  Assets/Art/BRIDGE picketfence.obj.meta
  Assets/Art/MOUNTAIN tunnelled.mtl.meta
  Assets/Art/MOUNTAIN tunnelled.obj.meta
  Assets/Art/TRACK puzzle.mtl.meta
  Assets/Art/TRACK puzzle.obj.meta
  Assets/TestScenes/Reece/ReeceScene.unity
  Fortuna-1/.idea/.idea.Fortuna-1/.idea/.gitignore
  Fortuna-1/.idea/.idea.Fortuna-1/.idea/discord.xml
  Fortuna-1/.idea/.idea.Fortuna-1/.idea/indexLayout.xml
  Fortuna-1/.idea/.idea.Fortuna-1/.idea/vcs.xml
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/TagManager.asset
Labels: design

#125 Separate World vehicle pieces
  Assets/Art/World Export/Tire back left unwrapped.mtl
  Assets/Art/World Export/Tire back left unwrapped.obj
  Assets/Art/World Export/Tire back right unwrapped.mtl
  Assets/Art/World Export/Tire back right unwrapped.obj
  Assets/Art/World Export/Tire front left unwrapped.mtl
  Assets/Art/World Export/Tire front left unwrapped.obj
  Assets/Art/World Export/Tire front right unwrapped.mtl
  Assets/Art/World Export/Tire front right unwrapped.obj
  Assets/Art/World Export/World vehicle.mtl
  Assets/Art/World Export/World vehicle.obj
Labels: art

#126 Separate Sun vehicle pieces
  Assets/Art/Sun Export/Sun vehicle.mtl
  Assets/Art/Sun Export/Sun vehicle.obj
  Assets/Art/Sun Export/Tire back left unwrapped.mtl
  Assets/Art/Sun Export/Tire back left unwrapped.obj
  Assets/Art/Sun Export/Tire back right unwrapped.mtl
  Assets/Art/Sun Export/Tire back right unwrapped.obj
  Assets/Art/Sun Export/Tire front left unwrapped.mtl
  Assets/Art/Sun Export/Tire front left unwrapped.obj
  Assets/Art/Sun Export/Tire front right unwrapped.mtl
  Assets/Art/Sun Export/Tire front right unwrapped.obj
Labels: art

#128 Track Puzzle Pieces
  Assets/Art/Puzzle pieces/Corners/Dips/Corner Bottom Left Dips.mtl
  Assets/Art/Puzzle pieces/Corners/Dips/Corner Bottom Left Dips.obj
  Assets/Art/Puzzle pieces/Corners/Dips/Corner Bottom Right Dips.mtl
  Assets/Art/Puzzle pieces/Corners/Dips/Corner Bottom Right Dips.obj
  Assets/Art/Puzzle pieces/Corners/Dips/Corner Top Left Dips.mtl
  Assets/Art/Puzzle pieces/Corners/Dips/Corner Top Left Dips.obj
  Assets/Art/Puzzle pieces/Corners/Dips/Corner Top Right Dips.mtl
  Assets/Art/Puzzle pieces/Corners/Dips/Corner Top Right Dips.obj
  Assets/Art/Puzzle pieces/Corners/Knobs/Corner Bottom Left Knobs.mtl
  Assets/Art/Puzzle pieces/Corners/Knobs/Corner Bottom Left Knobs.obj
  Assets/Art/Puzzle pieces/Corners/Knobs/Corner Bottom Right Knobs.mtl
  Assets/Art/Puzzle pieces/Corners/Knobs/Corner Bottom Right Knobs.obj
  Assets/Art/Puzzle pieces/Corners/Knobs/Corner Top Left Knobs.mtl
  Assets/Art/Puzzle pieces/Corners/Knobs/Corner Top Left Knobs.obj
  Assets/Art/Puzzle pieces/Corners/Knobs/Corner Top Right Knobs.mtl
  Assets/Art/Puzzle pieces/Corners/Knobs/Corner Top Right Knobs.obj
  Assets/Art/Puzzle pieces/Diagonals/Dips/Diagonal RTL Dips.mtl
  Assets/Art/Puzzle pieces/Diagonals/Dips/Diagonal RTL Dips.obj
  Assets/Art/Puzzle pieces/Diagonals/Dips/Straight Diagonal LTR Dips.mtl
  Assets/Art/Puzzle pieces/Diagonals/Dips/Straight Diagonal LTR Dips.obj
  Assets/Art/Puzzle pieces/Diagonals/Knobs/Diagonal LTR Knobs.mtl
  Assets/Art/Puzzle pieces/Diagonals/Knobs/Diagonal LTR Knobs.obj
  Assets/Art/Puzzle pieces/Diagonals/Knobs/Diagonal RTL Knobs.mtl
  Assets/Art/Puzzle pieces/Diagonals/Knobs/Diagonal RTL Knobs.obj
  Assets/Art/Puzzle pieces/Straights/Horizontal Drips.mtl
  Assets/Art/Puzzle pieces/Straights/Horizontal Drips.obj
  Assets/Art/Puzzle pieces/Straights/Horizontal Knobs.mtl
  Assets/Art/Puzzle pieces/Straights/Horizontal Knobs.obj
  Assets/Art/Puzzle pieces/Straights/Vertical Dips.mtl
  Assets/Art/Puzzle pieces/Straights/Vertical Dips.obj
  Assets/Art/Puzzle pieces/Straights/Vertical Knobs.mtl
  Assets/Art/Puzzle pieces/Straights/Vertical Knobs.obj
  Assets/Art/Puzzle pieces/Turns/Dips/Bottom Turn RTL Dips.mtl
  Assets/Art/Puzzle pieces/Turns/Dips/Bottom Turn RTL Dips.obj
  Assets/Art/Puzzle pieces/Turns/Dips/Bottom turn LTR dips.fbx
  Assets/Art/Puzzle pieces/Turns/Dips/Top Turn LTR Dips.mtl
  Assets/Art/Puzzle pieces/Turns/Dips/Top Turn LTR Dips.obj
  Assets/Art/Puzzle pieces/Turns/Dips/Top Turn RTL Dips.mtl
  Assets/Art/Puzzle pieces/Turns/Dips/Top Turn RTL Dips.obj
  Assets/Art/Puzzle pieces/Turns/Knobs/Bottom Turn LTR Knobs.mtl
  Assets/Art/Puzzle pieces/Turns/Knobs/Bottom Turn LTR Knobs.obj
  Assets/Art/Puzzle pieces/Turns/Knobs/Bottom Turn RTL Knobs.mtl
  Assets/Art/Puzzle pieces/Turns/Knobs/Bottom Turn RTL Knobs.obj
  Assets/Art/Puzzle pieces/Turns/Knobs/Top Turn LTR Knobs.mtl
  Assets/Art/Puzzle pieces/Turns/Knobs/Top Turn LTR Knobs.obj
  Assets/Art/Puzzle pieces/Turns/Knobs/Top Turn RTL Knobs.mtl
  Assets/Art/Puzzle pieces/Turns/Knobs/Top Turn RTL Knobs.obj
Labels: art

#130 Pocketwatch swinging obstacle
  Assets/Art/Obstacles/Swinging Obstacle Pocketwatch.mtl
  Assets/Art/Obstacles/Swinging Obstacle Pocketwatch.obj
Labels: art

#149 Audio implementation
  .idea/.idea.Fortuna-1/.idea/workspace.xml
  Assets/Audio/ReeceSFX.meta
  Assets/Audio/ReeceSFX/GameplaySFX.meta
  Assets/Audio/ReeceSFX/GameplaySFX/Collect_Arp_SFX01.wav
  Assets/Audio/ReeceSFX/GameplaySFX/Collect_Arp_SFX01.wav.meta
  Assets/Audio/ReeceSFX/GameplaySFX/Collect_PitchUp_SFX01.wav
  Assets/Audio/ReeceSFX/GameplaySFX/Collect_PitchUp_SFX01.wav.meta
  Assets/Audio/ReeceSFX/GameplaySFX/Vehicle.meta
  Assets/Audio/ReeceSFX/GameplaySFX/Vehicle/BrakeSFX.wav
  Assets/Audio/ReeceSFX/GameplaySFX/Vehicle/BrakeSFX.wav.meta
  Assets/Audio/ReeceSFX/GameplaySFX/Vehicle/EngineRunning.wav
  Assets/Audio/ReeceSFX/GameplaySFX/Vehicle/EngineRunning.wav.meta
  Assets/Audio/ReeceSFX/Music.meta
  Assets/Audio/ReeceSFX/Music/Cheerful Annoyance.ogg
  Assets/Audio/ReeceSFX/Music/Cheerful Annoyance.ogg.meta
  Assets/Audio/ReeceSFX/Music/Flowing Rocks.ogg
  Assets/Audio/ReeceSFX/Music/Flowing Rocks.ogg.meta
  Assets/Audio/ReeceSFX/PowerupSFX.meta
  Assets/Audio/ReeceSFX/PowerupSFX/BallLaunchSFX.wav
  Assets/Audio/ReeceSFX/PowerupSFX/BallLaunchSFX.wav.meta
  Assets/Audio/ReeceSFX/PowerupSFX/BonesUseSFX.wav
  Assets/Audio/ReeceSFX/PowerupSFX/BonesUseSFX.wav.meta
  Assets/Audio/ReeceSFX/PowerupSFX/CatnipUseSFX.wav
  Assets/Audio/ReeceSFX/PowerupSFX/CatnipUseSFX.wav.meta
  Assets/Audio/ReeceSFX/PowerupSFX/CrystalsPlaceSFX.wav
  Assets/Audio/ReeceSFX/PowerupSFX/CrystalsPlaceSFX.wav.meta
  Assets/Audio/ReeceSFX/PowerupSFX/MindsEyeSFX.wav
  Assets/Audio/ReeceSFX/PowerupSFX/MindsEyeSFX.wav.meta
  Assets/Audio/ReeceSFX/PowerupSFX/SpeedBoostSFX.wav
  Assets/Audio/ReeceSFX/PowerupSFX/SpeedBoostSFX.wav.meta
  Assets/Audio/ReeceSFX/UISFX.meta
  Assets/Audio/ReeceSFX/UISFX/ClickTone_NoReverb_SFX01.wav
  Assets/Audio/ReeceSFX/UISFX/ClickTone_NoReverb_SFX01.wav.meta
  Assets/Audio/ReeceSFX/UISFX/ClickTone_SFX01.wav
  Assets/Audio/ReeceSFX/UISFX/ClickTone_SFX01.wav.meta
  Assets/MainMixer.mixer
  Assets/Scripts/AudioSystem/AudioManager.cs
  Assets/Scripts/AudioSystem/EngineAudio.cs
  Assets/Scripts/AudioSystem/EngineAudio.cs.meta
  Assets/Scripts/PowerupSystem/PowerupBox.cs
  Assets/Scripts/PowerupSystem/PowerupContainer.cs
  Assets/TestScenes/Reece/ReeceScene.unity
Labels: design

#150 PositionTracking
  Assets/Scripts/CartLap.cs
  Assets/Scripts/PositionTracking.cs
  Assets/Scripts/PositionTracking.cs.meta
  Assets/TestScenes/Keenan/KeenanScene.unity
Labels: programming
