Repository BetaPuddi/Fortuna-1, pull requests merged in 2023-12, with the labels that each got.

#155 Powerup particle fx
  .idea/.idea.Fortuna-1/.idea/workspace.xml
  Assets/Scripts/PowerupSystem/BoneTrap.cs
  Assets/Scripts/PowerupSystem/CrystalTrap.cs
  Assets/Scripts/PowerupSystem/PowerupContainer.cs
  Assets/TestScenes/Reece/ParticleFX.meta
  Assets/TestScenes/Reece/ParticleFX/SmokeParticle.png
  Assets/TestScenes/Reece/ParticleFX/SmokeParticle.png.meta
  Assets/TestScenes/Reece/ReeceScene.unity
  Assets/TestScenes/Reece/TestMaterials/SmokeMaterial.mat
  Assets/TestScenes/Reece/TestMaterials/SmokeMaterial.mat.meta
  Assets/TestScenes/Reece/TestPrefabs/Crystals.prefab
Labels: design

#161 Adding shit to the main scenes
  .idea/.idea.Fortuna-1/.idea/workspace.xml
  Assets/Scenes/Levels/Level01.unity
  Assets/Scripts/HUD.meta
  Assets/Scripts/HUD/HUDFunctionality.cs
  Assets/Scripts/HUD/HUDFunctionality.cs.meta
  Assets/TestScenes/Reece/TestIcons.meta
  Assets/TestScenes/Reece/TestIcons/1stP.png
  Assets/TestScenes/Reece/TestIcons/1stP.png.meta
  Assets/TestScenes/Reece/TestIcons/Bone.png
  Assets/TestScenes/Reece/TestIcons/Bone.png.meta
  Assets/TestScenes/Reece/TestIcons/Catnip.png
  Assets/TestScenes/Reece/TestIcons/Catnip.png.meta
  Assets/TestScenes/Reece/TestIcons/Crystal.png
  Assets/TestScenes/Reece/TestIcons/Crystal.png.meta
  Assets/TestScenes/Reece/TestIcons/Noop.png
  Assets/TestScenes/Reece/TestIcons/Noop.png.meta
  Assets/TestScenes/Reece/TestIcons/Shoot.png
  Assets/TestScenes/Reece/TestIcons/Shoot.png.meta
  Assets/TestScenes/Reece/TestIcons/Speed.png
  Assets/TestScenes/Reece/TestIcons/Speed.png.meta
  Assets/TestScenes/Reece/TestMaterials/Tracker.mat
  Assets/TestScenes/Reece/TestMaterials/Tracker.mat.meta
Labels: design, management

#168 Sun Materials
  Assets/Textures/Sun.mat
  Assets/Textures/Sun.mat.meta
  Assets/Textures/Sun_Model_DefaultMaterial_BaseColor.png
  Assets/Textures/Sun_Model_DefaultMaterial_BaseColor.png.meta
  Assets/Textures/Sun_Model_DefaultMaterial_Height.png
  Assets/Textures/Sun_Model_DefaultMaterial_Height.png.meta
  Assets/Textures/Sun_Model_DefaultMaterial_Metallic.png
  Assets/Textures/Sun_Model_DefaultMaterial_Metallic.png.meta
  Assets/Textures/Sun_Model_DefaultMaterial_Normal.png
  Assets/Textures/Sun_Model_DefaultMaterial_Normal.png.meta
  Assets/Textures/Sun_Model_DefaultMaterial_Roughness.png
  Assets/Textures/Sun_Model_DefaultMaterial_Roughness.png.meta
Labels: art

#171 Art Assets
  Assets/Art/Powerup Icons.meta
  Assets/Art/Powerup Icons/Catnip.png
  Assets/Art/Powerup Icons/Catnip.png.meta
  Assets/Art/Powerup Icons/Divination.png
  Assets/Art/Powerup Icons/Divination.png.meta
  Assets/Art/Powerup Icons/DreamCatcher.png
  Assets/Art/Powerup Icons/DreamCatcher.png.meta
  Assets/Art/Powerup Icons/Mind's Eye.png
  Assets/Art/Powerup Icons/Mind's Eye.png.meta
  Assets/Art/Select_Death.png
  Assets/Art/Select_Death.png.meta
  Assets/Art/Select_Fool.png
  Assets/Art/Select_Fool.png.meta
  Assets/Art/Select_Lover.png
  Assets/Art/Select_Lover.png.meta
  Assets/Art/Select_Moon.png
  Assets/Art/Select_Moon.png.meta
  Assets/Art/Select_Sun.png
  Assets/Art/Select_Sun.png.meta
Labels: art

#172 Placeholder intro scene
  .idea/.idea.Fortuna-1/.idea/workspace.xml
  Assets/IntroAndSplash.meta
  Assets/IntroAndSplash/TEMPProject_start_screen_final.png
  Assets/IntroAndSplash/TEMPProject_start_screen_final.png.meta
  Assets/IntroAndSplash/UoN_Icon__logotype_horizontal_Black.png
  Assets/IntroAndSplash/UoN_Icon__logotype_horizontal_Black.png.meta
  Assets/IntroAndSplash/UoN_Icon__logotype_horizontal_White.png
  Assets/IntroAndSplash/UoN_Icon__logotype_horizontal_White.png.meta
  Assets/Scenes/Intro.unity
  Assets/Scenes/Intro.unity.meta
  Assets/Scripts/Intro.meta
  Assets/Scripts/Intro/IntroTransition.cs
  Assets/Scripts/Intro/IntroTransition.cs.meta
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/ProjectSettings.asset
Labels: design

#175 Camera Fixed
  Assets/Prefabs/BasicCarPlayer.prefab
  Assets/Prefabs/Main Camera 1.prefab
  Assets/Prefabs/Main Camera 1.prefab.meta
  Assets/Scenes/Levels/Level01.unity
Labels: design

#193 Placement number assets
  Assets/Art/Placement art/Eight place.png
  Assets/Art/Placement art/Fifth place.png
  Assets/Art/Placement art/First place.png
  Assets/Art/Placement art/Fourth place.png
  Assets/Art/Placement art/Ninth place.png
  Assets/Art/Placement art/Second place.png
  Assets/Art/Placement art/Seventh place.png
  Assets/Art/Placement art/Sixth place.png
  Assets/Art/Placement art/Third place.png
  Assets/Art/Placement art/Zeroth place.png
Labels: art

#194 Changed Values and Spawn Positions
  .idea/.idea.Fortuna-1/.idea/workspace.xml
  Assets/Prefabs/BasicCarAI.prefab
  Assets/Prefabs/BasicCarPlayer.prefab
  Assets/Scripts/PowerupSystem/BallProjectile.cs
  Assets/TestScenes/Reece/TestPrefabs/BallProjectile.prefab
Labels: design

#195 Applied Position Images
  .idea/.idea.Fortuna-1/.idea/workspace.xml
  Assets/Art/Placement art.meta
  Assets/Art/Placement art/Eight place.png.meta
  Assets/Art/Placement art/Fifth place.png.meta
  Assets/Art/Placement art/First place.png.meta
  Assets/Art/Placement art/Fourth place.png.meta
  Assets/Art/Placement art/Ninth place.png.meta
  Assets/Art/Placement art/Second place.png.meta
  Assets/Art/Placement art/Seventh place.png.meta
  Assets/Art/Placement art/Sixth place.png.meta
  Assets/Art/Placement art/Third place.png.meta
  Assets/Art/Placement art/Zeroth place.png.meta
  Assets/Scenes/Levels/Level01.unity
  Assets/Scripts/HUD/HUDFunctionality.cs
Labels: design

#196 Why is donas taken newbranch
  Assets/Art/BRIDGE picketfence.mtl.meta
  Assets/Art/BRIDGE picketfence.obj
  Assets/Art/Cassettes/CassettePile.obj
  Assets/Art/Cassettes/CassettePile.obj.meta
  Assets/Art/Cassettes/CassetteSolo.obj
  Assets/Art/Cassettes/CassetteSolo.obj.meta
  Assets/Art/MOUNTAIN tunnelled.mtl.meta
  Assets/Art/MOUNTAIN tunnelled.obj
  Assets/Art/TRACK puzzle.mtl.meta
  Assets/Art/TRACK puzzle.obj
  Assets/Models/Reimported Models/Vehicle.zip
Labels: help wanted

#207 Create second track
  Assets/TestScenes/Jacob/Level02.unity
  Assets/TestScenes/Jacob/Level02.unity.meta
Labels: design

#209 Main menu audio/UI implementation
  .idea/.idea.Fortuna-1/.idea/workspace.xml
  Assets/Audio/ReeceSFX/Music/Drumming Sticks.ogg
  Assets/Audio/ReeceSFX/Music/Drumming Sticks.ogg.meta
  Assets/Scenes/MainMenu.unity
  Assets/Scripts/UI.meta
  Assets/Scripts/UI/HUDFunctionality.cs
  Assets/Scripts/UI/HUDFunctionality.cs.meta
  Assets/Scripts/UI/StartScreenEffects.cs
  Assets/Scripts/UI/StartScreenEffects.cs.meta
Labels: design
